name='Configify',
version='0.0.1.dev1',
description='Allows end-user Configuration generation for development.'
long_description='A package for developers who want to offer other end-user-developers of their tools to more easily create the right type of configuration files.',
url='https://github.com/dyspop/Configify',
author='Dan Black',
author_email='dyspop@gmail.com',
license='GPL-3.0+',
classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
     'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 2',
    'Programming Language :: Python :: 2.6',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.2',
    'Programming Language :: Python :: 3.3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
],
keywords=['config', 'configuration generator', 'dev tool', 'json'],
project_urls={ 'Documentation': 'https://github.com/dyspop/Configify/README.md' },
packages=find_packages(['json', 'os'], exclude=['tests*']),
install_requires=[],
